//
//  APIParameterLanguage.swift
//  Future News
//
//  Created by Danya Denisiuk on 14.02.2024.
//

import Foundation

extension APIURLConfig {
    enum APIParameterLanguage: String {
        case afar = "aa"
        case amharic = "am"
        case arabic = "ar"
        case bengali = "bn"
        case bosnian = "bs"
        case bulgarian = "bg"
        case burmese = "my"
        case chinese = "zh"
        case croatian = "hr"
        case czech = "cs"
        case danish = "da"
        case dutch = "nl"
        case english = "en"
        case estonian = "et"
        case finnish = "fi"
        case french = "fr"
        case german = "de"
        case greek = "el"
        case hebrew = "he"
        case hindi = "hi"
        case hungarian = "hu"
        case icelandic = "is"
        case indonesian = "id"
        case italian = "it"
        case japanese = "ja"
        case korean = "ko"
        case lao = "lo"
        case latvian = "lv"
        case lithuanian = "lt"
        case macedonian = "mk"
        case malay = "ms"
        case maltese = "mt"
        case marathi = "mr"
        case maori = "mi"
        case nepali = "ne"
        case norwegian = "nb"
        case persian = "fa"
        case polish = "pl"
        case portuguese = "pt"
        case pomanian = "ro"
        case russian = "ru"
        case serbian = "sr"
        case sinhalese = "si"
        case slovak = "sk"
        case slovene = "sl"
        case somali = "so"
        case spanish = "es"
        case swedish = "sv"
        case tajik = "tg"
        case tamil = "ta"
        case telugu = "te"
        case thai = "th"
        case turkish = "tr"
        case ukrainian = "uk"
        case urdu = "ur"
        case uzbek = "uz"
        case vietnamese = "vi"
    }
}
